defaults:
  - _self_
  - override hydra/job_logging: none # hydraで自動的にログファイルが生成されるのを防ぐ

debug: False
seed: 113
fold_num: 5
als:
  factors: 100
  regularization: 0.05
  alpha: 2.0
  calculate_training_loss: True
  iterations: 15
gbdt:
  lgb:
    model_params:
      num_boost_round: 10000
      objective: binary
      metric: binary_logloss
      random_state: 42
      boosting_type: gbdt
      verbose: -1
      seed: 42
      feature_fraction: 0.8
      bagging_fraction: 0.8
      bagging_freq: 1
      num_leaves: 31
      min_data_in_leaf: 20
      max_depth: 5
      max_bin: 255
      n_jobs: -1
      importance_type: gain
    train_params:
      early_stopping_rounds: 50
  cat:
    model_params:
      iterations: 10000
      loss_function: Logloss
      random_seed: 42
      early_stopping_rounds: 50
      task_type: GPU
    train_params:
      verbose_eval: 250
      early_stopping_round: 50

feature:
  SessionYadoRaw:
    feature_cols:
      - seq_no
    key_cols:
      - yad_no
      - session_id
  YadoRaw:
    feature_cols:
      - yad_type
      - total_room_cnt
      - wireless_lan_flg
      - onsen_flg
      - kd_stn_5min
      - kd_bch_5min
      - kd_slp_5min
      - kd_conv_walk_5min
      - wid_cd
      - ken_cd
      - lrg_cd
      - sml_cd
    key_cols:
      - yad_no
  Session: # ぜんぶ　null # null # null # null # null
    feature_cols:
      - user_mode_wid_cd
      - user_mode_ken_cd
      - user_mode_lrg_cd
      - user_mode_sml_cd
      - user_seq_cnt
      - user_mean_total_room_cnt
      - user_mean_wireless_lan_flg
      - user_mean_onsen_flg
      - user_mean_kd_stn_5min
      - user_mean_kd_bch_5min
      - user_mean_kd_slp_5min
      - user_mean_kd_conv_walk_5min
    key_cols:
      - session_id
  YadoRank:
    feature_cols:
      - yad_cnt
      - yad_cnt_rank
      - yad_cnt_rank_wid_cd
      - yad_cnt_rank_ken_cd
      - yad_cnt_rank_lrg_cd
      - yad_cnt_rank_sml_cd
    key_cols:
      - yad_no
  MatchModeCD:
    feature_cols: # 全部null
      - is_match_mode_wid_cd
      - is_match_mode_ken_cd
      - is_match_mode_lrg_cd
      - is_match_mode_sml_cd
    key_cols:
      - session_id
      - yad_no
  YadoSesMean:
    feature_cols:
      - this_session_seq_len_yad_mean
      - another_session_seq_len_yad_mean
      - this_count_yad_mean
      - another_count_yad_mean
      - this_ratio_yad_mean
      - another_ratio_yad_mean
    key_cols:
      - yad_no

hydra:
  # hydraで自動的にログファイルが生成されるのを防ぐ
  output_subdir: null
  job:
    chdir: False
